name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Updates every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: activity, community, repositories
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: public
          committer_branch: main
          committer_message: "chore: update GitHub metrics"
